/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ber_pattern_generator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6815aa6a75d93cb9cee980ef5dfa0158)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ofdm_testbed/ber_pattern_generator.h>
// pydoc.h is automatically generated in the build directory
#include <ber_pattern_generator_pydoc.h>

void bind_ber_pattern_generator(py::module& m)
{

    using ber_pattern_generator    = ::gr::ofdm_testbed::ber_pattern_generator;


    py::class_<ber_pattern_generator, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ber_pattern_generator>>(m, "ber_pattern_generator", D(ber_pattern_generator))

        .def(py::init(&ber_pattern_generator::make),
           py::arg("error_rate"),
           py::arg("pattern_len"),
           D(ber_pattern_generator,make)
        )
        




        
        .def("set_error_rate",&ber_pattern_generator::set_error_rate,       
            py::arg("error_rate"),
            D(ber_pattern_generator,set_error_rate)
        )

        ;




}








