/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bpsk_mapper.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a7fda191087fa25613f065eabe001194)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ofdm_testbed/bpsk_mapper.h>
// pydoc.h is automatically generated in the build directory
#include <bpsk_mapper_pydoc.h>

void bind_bpsk_mapper(py::module& m)
{

    using bpsk_mapper    = ::gr::ofdm_testbed::bpsk_mapper;


    py::class_<bpsk_mapper, gr::block, gr::basic_block,
        std::shared_ptr<bpsk_mapper>>(m, "bpsk_mapper", D(bpsk_mapper))

        .def(py::init(&bpsk_mapper::make),
           D(bpsk_mapper,make)
        )
        



        ;




}








