/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(byte_to_bit.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(56b9fedfa2143adc75ee2cd195687de5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ofdm_testbed/byte_to_bit.h>
// pydoc.h is automatically generated in the build directory
#include <byte_to_bit_pydoc.h>

void bind_byte_to_bit(py::module& m)
{

    using byte_to_bit    = ::gr::ofdm_testbed::byte_to_bit;


    py::class_<byte_to_bit, gr::block, gr::basic_block,
        std::shared_ptr<byte_to_bit>>(m, "byte_to_bit", D(byte_to_bit))

        .def(py::init(&byte_to_bit::make),
           D(byte_to_bit,make)
        )
        



        ;




}








