/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(receiver_control_p2p.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4221eb8202f6e3cf48b17c5a446bc9bd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ofdm_testbed/receiver_control_p2p.h>
// pydoc.h is automatically generated in the build directory
#include <receiver_control_p2p_pydoc.h>

void bind_receiver_control_p2p(py::module& m)
{

    using receiver_control_p2p    = ::gr::ofdm_testbed::receiver_control_p2p;


    py::class_<receiver_control_p2p, gr::block, gr::basic_block,
        std::shared_ptr<receiver_control_p2p>>(m, "receiver_control_p2p", D(receiver_control_p2p))

        .def(py::init(&receiver_control_p2p::make),
           py::arg("packet_size"),
           py::arg("transmitter_id"),
           py::arg("receiver_id"),
           D(receiver_control_p2p,make)
        )
        



        ;




}








