/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zero_elimination.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c1784c16fd6e6aa13feb6ef14a4d880d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ofdm_testbed/zero_elimination.h>
// pydoc.h is automatically generated in the build directory
#include <zero_elimination_pydoc.h>

void bind_zero_elimination(py::module& m)
{

    using zero_elimination    = ::gr::ofdm_testbed::zero_elimination;


    py::class_<zero_elimination, gr::block, gr::basic_block,
        std::shared_ptr<zero_elimination>>(m, "zero_elimination", D(zero_elimination))

        .def(py::init(&zero_elimination::make),
           py::arg("node_id"),
           py::arg("data_len"),
           D(zero_elimination,make)
        )
        



        ;




}








