/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ofdm_testbed
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_OFDM_TESTBED_API_H
#define INCLUDED_OFDM_TESTBED_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ofdm_testbed_EXPORTS
#define OFDM_TESTBED_API __GR_ATTR_EXPORT
#else
#define OFDM_TESTBED_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_OFDM_TESTBED_API_H */
